# app/pdf.py
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from reportlab.lib.colors import HexColor

def itinerary_pdf(buf, origin, destination, itinerary: dict):
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4
    y = height - 2*cm

    c.setFillColor(HexColor('#111111'))
    c.setFont("Helvetica-Bold", 16)
    c.drawString(2*cm, y, "ATIS — Trip Summary")
    y -= 1.2*cm

    c.setFont("Helvetica", 11)
    c.drawString(2*cm, y, f"Origin:  {origin[0]:.5f}, {origin[1]:.5f}")
    y -= 0.6*cm
    c.drawString(2*cm, y, f"Destination:  {destination[0]:.5f}, {destination[1]:.5f}")
    y -= 0.8*cm

    c.setFont("Helvetica-Bold", 12)
    c.drawString(2*cm, y, "Selected Itinerary")
    y -= 0.6*cm
    c.setFont("Helvetica", 11)
    c.drawString(2*cm, y, f"Duration: ~{itinerary.get('durationMin')} min   Transfers: {itinerary.get('transfers')}")
    y -= 0.6*cm
    c.drawString(2*cm, y, f"Walk: {itinerary.get('walk_km', 0):.1f} km   Modes: {', '.join(itinerary.get('modes', []))}")
    y -= 0.8*cm

    c.setFont("Helvetica-Bold", 12)
    c.drawString(2*cm, y, "Legs")
    y -= 0.6*cm
    c.setFont("Helvetica", 11)
    for leg in itinerary.get("legs", []):
        c.drawString(2.5*cm, y, f"• {leg}")
        y -= 0.5*cm
        if y < 2*cm:
            c.showPage()
            y = height - 2*cm
            c.setFont("Helvetica", 11)

    c.setFont("Helvetica-Oblique", 10)
    y -= 0.6*cm
    c.setFillColor(HexColor('#444444'))
    c.drawString(2*cm, y, "Generated by ATIS demo (v0.4)")
    c.save()
